repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.54.1
    hooks:
    -   id: golangci-lint
        args: ['--timeout', '5m']
        exclude: ^vendor/

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
