name: pre-commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.0
